version: '3'
services:
  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end-image
    depends_on:
      - back-end
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end-image
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-image
    depends_on:
      - front-end
      - back-end
    ports:
      - "80:80"